/* Lips of Suna
 * Copyright© 2007-2010 Lips of Suna development team.
 *
 * Lips of Suna is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Lips of Suna is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Lips of Suna. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \addtogroup livid Video
 * @{
 * \addtogroup LIVidCalls Calls
 * @{
 */

#include <lipsofsuna/system.h>
#include "video-calls.h"

int
livid_calls_init (LIVidCalls* self)
{
	/* SDL calls. */
#define CALL(name) self->name = name;
	CALL (SDL_ConvertSurface);
	CALL (SDL_Delay);
	CALL (SDL_EnableKeyRepeat);
	CALL (SDL_EnableUNICODE);
	CALL (SDL_EventState);
	CALL (SDL_FreeSurface);
	CALL (SDL_GetModState);
	CALL (SDL_GetMouseState);
	CALL (SDL_GetRelativeMouseState);
	CALL (SDL_GetTicks);
	CALL (SDL_GetVideoSurface);
	CALL (SDL_GL_SetAttribute);
	CALL (SDL_GL_SwapBuffers);
	CALL (SDL_WM_GrabInput);
	CALL (SDL_Init);
	CALL (SDL_JoystickClose);
	CALL (SDL_JoystickOpen);
	CALL (SDL_PollEvent);
	CALL (SDL_Quit);
	CALL (SDL_SetVideoMode);
	CALL (SDL_ShowCursor);
	CALL (SDL_WarpMouse);
	CALL (SDL_WM_SetCaption);
#undef CALL

	/* SDL_ttf calls. */
#define CALL(name) self->name = name;
	CALL (TTF_CloseFont);
	CALL (TTF_FontLineSkip);
	CALL (TTF_FontAscent);
	CALL (TTF_FontDescent);
	CALL (TTF_FontHeight);
	CALL (TTF_GlyphMetrics);
	CALL (TTF_Init);
	CALL (TTF_OpenFont);
	CALL (TTF_Quit);
	CALL (TTF_RenderGlyph_Blended);
	CALL (TTF_WasInit);
#undef CALL

	/* OpenGL calls. */
#define CALL(name) self->name = name;
	CALL (glAccum);
	CALL (glAlphaFunc);
	CALL (glAreTexturesResident);
	CALL (glArrayElement);
	CALL (glBegin);
	CALL (glBindTexture);
	CALL (glBitmap);
	CALL (glBlendFunc);
	CALL (glCallList);
	CALL (glCallLists);
	CALL (glClear);
	CALL (glClearAccum);
	CALL (glClearColor);
	CALL (glClearDepth);
	CALL (glClearIndex);
	CALL (glClearStencil);
	CALL (glClipPlane);
	CALL (glColor3b);
	CALL (glColor3bv);
	CALL (glColor3d);
	CALL (glColor3dv);
	CALL (glColor3f);
	CALL (glColor3fv);
	CALL (glColor3i);
	CALL (glColor3iv);
	CALL (glColor3s);
	CALL (glColor3sv);
	CALL (glColor3ub);
	CALL (glColor3ubv);
	CALL (glColor3ui);
	CALL (glColor3uiv);
	CALL (glColor3us);
	CALL (glColor3usv);
	CALL (glColor4b);
	CALL (glColor4bv);
	CALL (glColor4d);
	CALL (glColor4dv);
	CALL (glColor4f);
	CALL (glColor4fv);
	CALL (glColor4i);
	CALL (glColor4iv);
	CALL (glColor4s);
	CALL (glColor4sv);
	CALL (glColor4ub);
	CALL (glColor4ubv);
	CALL (glColor4ui);
	CALL (glColor4uiv);
	CALL (glColor4us);
	CALL (glColor4usv);
	CALL (glColorMask);
	CALL (glColorMaterial);
	CALL (glColorPointer);
	CALL (glCopyPixels);
	CALL (glCopyTexImage1D);
	CALL (glCopyTexImage2D);
	CALL (glCopyTexSubImage1D);
	CALL (glCopyTexSubImage2D);
	CALL (glCullFace);
	CALL (glDeleteLists);
	CALL (glDeleteTextures);
	CALL (glDepthFunc);
	CALL (glDepthMask);
	CALL (glDepthRange);
	CALL (glDisable);
	CALL (glDisableClientState);
	CALL (glDrawArrays);
	CALL (glDrawBuffer);
	CALL (glDrawElements);
	CALL (glDrawPixels);
	CALL (glEdgeFlag);
	CALL (glEdgeFlagPointer);
	CALL (glEdgeFlagv);
	CALL (glEnable);
	CALL (glEnableClientState);
	CALL (glEnd);
	CALL (glEndList);
	CALL (glEvalCoord1d);
	CALL (glEvalCoord1dv);
	CALL (glEvalCoord1f);
	CALL (glEvalCoord1fv);
	CALL (glEvalCoord2d);
	CALL (glEvalCoord2dv);
	CALL (glEvalCoord2f);
	CALL (glEvalCoord2fv);
	CALL (glEvalMesh1);
	CALL (glEvalMesh2);
	CALL (glEvalPoint1);
	CALL (glEvalPoint2);
	CALL (glFeedbackBuffer);
	CALL (glFinish);
	CALL (glFlush);
	CALL (glFogf);
	CALL (glFogfv);
	CALL (glFogi);
	CALL (glFogiv);
	CALL (glFrontFace);
	CALL (glFrustum);
	CALL (glGenLists);
	CALL (glGenTextures);
	CALL (glGetBooleanv);
	CALL (glGetClipPlane);
	CALL (glGetDoublev);
	CALL (glGetError);
	CALL (glGetFloatv);
	CALL (glGetIntegerv);
	CALL (glGetLightfv);
	CALL (glGetLightiv);
	CALL (glGetMapdv);
	CALL (glGetMapfv);
	CALL (glGetMapiv);
	CALL (glGetMaterialfv);
	CALL (glGetMaterialiv);
	CALL (glGetPixelMapfv);
	CALL (glGetPixelMapuiv);
	CALL (glGetPixelMapusv);
	CALL (glGetPointerv);
	CALL (glGetPolygonStipple);
	CALL (glGetString);
	CALL (glGetTexEnvfv);
	CALL (glGetTexEnviv);
	CALL (glGetTexGendv);
	CALL (glGetTexGenfv);
	CALL (glGetTexGeniv);
	CALL (glGetTexImage);
	CALL (glGetTexLevelParameterfv);
	CALL (glGetTexLevelParameteriv);
	CALL (glGetTexParameterfv);
	CALL (glGetTexParameteriv);
	CALL (glHint);
	CALL (glIndexMask);
	CALL (glIndexPointer);
	CALL (glIndexd);
	CALL (glIndexdv);
	CALL (glIndexf);
	CALL (glIndexfv);
	CALL (glIndexi);
	CALL (glIndexiv);
	CALL (glIndexs);
	CALL (glIndexsv);
	CALL (glIndexub);
	CALL (glIndexubv);
	CALL (glInitNames);
	CALL (glInterleavedArrays);
	CALL (glIsEnabled);
	CALL (glIsList);
	CALL (glIsTexture);
	CALL (glLightModelf);
	CALL (glLightModelfv);
	CALL (glLightModeli);
	CALL (glLightModeliv);
	CALL (glLightf);
	CALL (glLightfv);
	CALL (glLighti);
	CALL (glLightiv);
	CALL (glLineStipple);
	CALL (glLineWidth);
	CALL (glListBase);
	CALL (glLoadIdentity);
	CALL (glLoadMatrixd);
	CALL (glLoadMatrixf);
	CALL (glLoadName);
	CALL (glLogicOp);
	CALL (glMap1d);
	CALL (glMap1f);
	CALL (glMap2d);
	CALL (glMap2f);
	CALL (glMapGrid1d);
	CALL (glMapGrid1f);
	CALL (glMapGrid2d);
	CALL (glMapGrid2f);
	CALL (glMaterialf);
	CALL (glMaterialfv);
	CALL (glMateriali);
	CALL (glMaterialiv);
	CALL (glMatrixMode);
	CALL (glMultMatrixd);
	CALL (glMultMatrixf);
	CALL (glNewList);
	CALL (glNormal3b);
	CALL (glNormal3bv);
	CALL (glNormal3d);
	CALL (glNormal3dv);
	CALL (glNormal3f);
	CALL (glNormal3fv);
	CALL (glNormal3i);
	CALL (glNormal3iv);
	CALL (glNormal3s);
	CALL (glNormal3sv);
	CALL (glNormalPointer);
	CALL (glOrtho);
	CALL (glPassThrough);
	CALL (glPixelMapfv);
	CALL (glPixelMapuiv);
	CALL (glPixelMapusv);
	CALL (glPixelStoref);
	CALL (glPixelStorei);
	CALL (glPixelTransferf);
	CALL (glPixelTransferi);
	CALL (glPixelZoom);
	CALL (glPointSize);
	CALL (glPolygonMode);
	CALL (glPolygonOffset);
	CALL (glPolygonStipple);
	CALL (glPopAttrib);
	CALL (glPopClientAttrib);
	CALL (glPopMatrix);
	CALL (glPopName);
	CALL (glPrioritizeTextures);
	CALL (glPushAttrib);
	CALL (glPushClientAttrib);
	CALL (glPushMatrix);
	CALL (glPushName);
	CALL (glRasterPos2d);
	CALL (glRasterPos2dv);
	CALL (glRasterPos2f);
	CALL (glRasterPos2fv);
	CALL (glRasterPos2i);
	CALL (glRasterPos2iv);
	CALL (glRasterPos2s);
	CALL (glRasterPos2sv);
	CALL (glRasterPos3d);
	CALL (glRasterPos3dv);
	CALL (glRasterPos3f);
	CALL (glRasterPos3fv);
	CALL (glRasterPos3i);
	CALL (glRasterPos3iv);
	CALL (glRasterPos3s);
	CALL (glRasterPos3sv);
	CALL (glRasterPos4d);
	CALL (glRasterPos4dv);
	CALL (glRasterPos4f);
	CALL (glRasterPos4fv);
	CALL (glRasterPos4i);
	CALL (glRasterPos4iv);
	CALL (glRasterPos4s);
	CALL (glRasterPos4sv);
	CALL (glReadBuffer);
	CALL (glReadPixels);
	CALL (glRectd);
	CALL (glRectdv);
	CALL (glRectf);
	CALL (glRectfv);
	CALL (glRecti);
	CALL (glRectiv);
	CALL (glRects);
	CALL (glRectsv);
	CALL (glRenderMode);
	CALL (glRotated);
	CALL (glRotatef);
	CALL (glScaled);
	CALL (glScalef);
	CALL (glScissor);
	CALL (glSelectBuffer);
	CALL (glShadeModel);
	CALL (glStencilFunc);
	CALL (glStencilMask);
	CALL (glStencilOp);
	CALL (glTexCoord1d);
	CALL (glTexCoord1dv);
	CALL (glTexCoord1f);
	CALL (glTexCoord1fv);
	CALL (glTexCoord1i);
	CALL (glTexCoord1iv);
	CALL (glTexCoord1s);
	CALL (glTexCoord1sv);
	CALL (glTexCoord2d);
	CALL (glTexCoord2dv);
	CALL (glTexCoord2f);
	CALL (glTexCoord2fv);
	CALL (glTexCoord2i);
	CALL (glTexCoord2iv);
	CALL (glTexCoord2s);
	CALL (glTexCoord2sv);
	CALL (glTexCoord3d);
	CALL (glTexCoord3dv);
	CALL (glTexCoord3f);
	CALL (glTexCoord3fv);
	CALL (glTexCoord3i);
	CALL (glTexCoord3iv);
	CALL (glTexCoord3s);
	CALL (glTexCoord3sv);
	CALL (glTexCoord4d);
	CALL (glTexCoord4dv);
	CALL (glTexCoord4f);
	CALL (glTexCoord4fv);
	CALL (glTexCoord4i);
	CALL (glTexCoord4iv);
	CALL (glTexCoord4s);
	CALL (glTexCoord4sv);
	CALL (glTexCoordPointer);
	CALL (glTexEnvf);
	CALL (glTexEnvfv);
	CALL (glTexEnvi);
	CALL (glTexEnviv);
	CALL (glTexGend);
	CALL (glTexGendv);
	CALL (glTexGenf);
	CALL (glTexGenfv);
	CALL (glTexGeni);
	CALL (glTexGeniv);
	CALL (glTexImage1D);
	CALL (glTexImage2D);
	CALL (glTexParameterf);
	CALL (glTexParameterfv);
	CALL (glTexParameteri);
	CALL (glTexParameteriv);
	CALL (glTexSubImage1D);
	CALL (glTexSubImage2D);
	CALL (glTranslated);
	CALL (glTranslatef);
	CALL (glVertex2d);
	CALL (glVertex2dv);
	CALL (glVertex2f);
	CALL (glVertex2fv);
	CALL (glVertex2i);
	CALL (glVertex2iv);
	CALL (glVertex2s);
	CALL (glVertex2sv);
	CALL (glVertex3d);
	CALL (glVertex3dv);
	CALL (glVertex3f);
	CALL (glVertex3fv);
	CALL (glVertex3i);
	CALL (glVertex3iv);
	CALL (glVertex3s);
	CALL (glVertex3sv);
	CALL (glVertex4d);
	CALL (glVertex4dv);
	CALL (glVertex4f);
	CALL (glVertex4fv);
	CALL (glVertex4i);
	CALL (glVertex4iv);
	CALL (glVertex4s);
	CALL (glVertex4sv);
	CALL (glVertexPointer);
	CALL (glViewport);
#undef CALL

	return 1;
}

/** @} */
/** @} */
