/* Lips of Suna
 * Copyright© 2007-2010 Lips of Suna development team.
 *
 * Lips of Suna is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Lips of Suna is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Lips of Suna. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \addtogroup liren Render
 * @{
 * \addtogroup LIRenUniform Uniform
 * @{
 */

#ifndef __RENDER_UNIFORM_H__
#define __RENDER_UNIFORM_H__

#include <lipsofsuna/video.h>
#include "render-types.h"

enum
{
	LIREN_UNIFORM_NONE,
	LIREN_UNIFORM_CUBETEXTURE0,
	LIREN_UNIFORM_CUBETEXTURE1,
	LIREN_UNIFORM_CUBETEXTURE2,
	LIREN_UNIFORM_CUBETEXTURE3,
	LIREN_UNIFORM_CUBETEXTURE4,
	LIREN_UNIFORM_CUBETEXTURE5,
	LIREN_UNIFORM_CUBETEXTURE6,
	LIREN_UNIFORM_CUBETEXTURE7,
	LIREN_UNIFORM_CUBETEXTURE8,
	LIREN_UNIFORM_CUBETEXTURE9,
	LIREN_UNIFORM_DIFFUSETEXTURE0,
	LIREN_UNIFORM_DIFFUSETEXTURE1,
	LIREN_UNIFORM_DIFFUSETEXTURE2,
	LIREN_UNIFORM_DIFFUSETEXTURE3,
	LIREN_UNIFORM_DIFFUSETEXTURE4,
	LIREN_UNIFORM_DIFFUSETEXTURE5,
	LIREN_UNIFORM_DIFFUSETEXTURE6,
	LIREN_UNIFORM_DIFFUSETEXTURE7,
	LIREN_UNIFORM_DIFFUSETEXTURE8,
	LIREN_UNIFORM_DIFFUSETEXTURE9,
	LIREN_UNIFORM_LIGHTMATRIX0,
	LIREN_UNIFORM_LIGHTMATRIX1,
	LIREN_UNIFORM_LIGHTMATRIX2,
	LIREN_UNIFORM_LIGHTMATRIX3,
	LIREN_UNIFORM_LIGHTMATRIX4,
	LIREN_UNIFORM_LIGHTMATRIX5,
	LIREN_UNIFORM_LIGHTMATRIX6,
	LIREN_UNIFORM_LIGHTMATRIX7,
	LIREN_UNIFORM_LIGHTMATRIX8,
	LIREN_UNIFORM_LIGHTMATRIX9,
	LIREN_UNIFORM_LIGHTPOSITION0,
	LIREN_UNIFORM_LIGHTPOSITION1,
	LIREN_UNIFORM_LIGHTPOSITION2,
	LIREN_UNIFORM_LIGHTPOSITION3,
	LIREN_UNIFORM_LIGHTPOSITION4,
	LIREN_UNIFORM_LIGHTPOSITION5,
	LIREN_UNIFORM_LIGHTPOSITION6,
	LIREN_UNIFORM_LIGHTPOSITION7,
	LIREN_UNIFORM_LIGHTPOSITION8,
	LIREN_UNIFORM_LIGHTPOSITION9,
	LIREN_UNIFORM_LIGHTTYPE0,
	LIREN_UNIFORM_LIGHTTYPE1,
	LIREN_UNIFORM_LIGHTTYPE2,
	LIREN_UNIFORM_LIGHTTYPE3,
	LIREN_UNIFORM_LIGHTTYPE4,
	LIREN_UNIFORM_LIGHTTYPE5,
	LIREN_UNIFORM_LIGHTTYPE6,
	LIREN_UNIFORM_LIGHTTYPE7,
	LIREN_UNIFORM_LIGHTTYPE8,
	LIREN_UNIFORM_LIGHTTYPE9,
	LIREN_UNIFORM_MATERIALDIFFUSE,
	LIREN_UNIFORM_MATERIALSHININESS,
	LIREN_UNIFORM_MATERIALSPECULAR,
	LIREN_UNIFORM_MODELMATRIX,
	LIREN_UNIFORM_MODELVIEWINVERSE,
	LIREN_UNIFORM_NOISETEXTURE,
	LIREN_UNIFORM_PARAM0,
	LIREN_UNIFORM_SHADOWTEXTURE0,
	LIREN_UNIFORM_SHADOWTEXTURE1,
	LIREN_UNIFORM_SHADOWTEXTURE2,
	LIREN_UNIFORM_SHADOWTEXTURE3,
	LIREN_UNIFORM_SHADOWTEXTURE4,
	LIREN_UNIFORM_SHADOWTEXTURE5,
	LIREN_UNIFORM_SHADOWTEXTURE6,
	LIREN_UNIFORM_SHADOWTEXTURE7,
	LIREN_UNIFORM_SHADOWTEXTURE8,
	LIREN_UNIFORM_SHADOWTEXTURE9,
	LIREN_UNIFORM_TIME
};

enum
{
	LIREN_UNIFORM_LIGHTTYPE_DISABLED    = 0,
	LIREN_UNIFORM_LIGHTTYPE_DIRECTIONAL = 1,
	LIREN_UNIFORM_LIGHTTYPE_POINT       = 2,
	LIREN_UNIFORM_LIGHTTYPE_SPOT        = 3,
	LIREN_UNIFORM_LIGHTTYPE_SPOTSHADOW  = 4
};

typedef struct _LIRenUniform LIRenUniform;
struct _LIRenUniform
{
	char* name;
	GLint binding;
	GLint sampler;
	int value;
};

static inline int
liren_uniform_get_sampler (LIRenUniform* self)
{
	if (self->value >= LIREN_UNIFORM_CUBETEXTURE0 &&
	    self->value <= LIREN_UNIFORM_CUBETEXTURE9)
		return 1;
	if (self->value >= LIREN_UNIFORM_DIFFUSETEXTURE0 &&
	    self->value <= LIREN_UNIFORM_DIFFUSETEXTURE9)
		return 1;
	if (self->value == LIREN_UNIFORM_NOISETEXTURE)
		return 1;
	if (self->value >= LIREN_UNIFORM_SHADOWTEXTURE0 &&
	    self->value <= LIREN_UNIFORM_SHADOWTEXTURE9)
		return 1;
	return 0;
}

#endif

/** @} */
/** @} */
