/* Lips of Suna
 * Copyright© 2007-2008 Lips of Suna development team.
 *
 * Lips of Suna is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Lips of Suna is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Lips of Suna. If not, see <http://www.gnu.org/licenses/>.
 */

#define GLAPI
#include <dlfcn.h>
#include <string.h>
#include <SDL/SDL.h>
#include "video-opengl.h"

static int initialized = 0;

/**
 * \brief Initializes the video subsystem.
 *
 * \param path Path to the OpenGL library or NULL.
 * \return Nonzero on success.
 */
int
livid_video_init (const char* path)
{
	if (initialized++)
		return 1;
	SDL_Init (SDL_INIT_VIDEO);

	glAreTexturesResidentEXT = dlsym (RTLD_DEFAULT, "glAreTexturesResidentEXT");
	glIsBufferARB = dlsym (RTLD_DEFAULT, "glIsBufferARB");
	glIsEnabledIndexedEXT = dlsym (RTLD_DEFAULT, "glIsEnabledIndexedEXT");
	glIsFramebufferEXT = dlsym (RTLD_DEFAULT, "glIsFramebufferEXT");
	glIsProgramARB = dlsym (RTLD_DEFAULT, "glIsProgramARB");
	glIsQueryARB = dlsym (RTLD_DEFAULT, "glIsQueryARB");
	glIsRenderbufferEXT = dlsym (RTLD_DEFAULT, "glIsRenderbufferEXT");
	glIsTextureEXT = dlsym (RTLD_DEFAULT, "glIsTextureEXT");
	glIsVariantEnabledEXT = dlsym (RTLD_DEFAULT, "glIsVariantEnabledEXT");
	glUnmapBufferARB = dlsym (RTLD_DEFAULT, "glUnmapBufferARB");
	glUnmapNamedBufferEXT = dlsym (RTLD_DEFAULT, "glUnmapNamedBufferEXT");
	glCheckFramebufferStatusEXT = dlsym (RTLD_DEFAULT, "glCheckFramebufferStatusEXT");
	glCheckNamedFramebufferStatusEXT = dlsym (RTLD_DEFAULT, "glCheckNamedFramebufferStatusEXT");
	glCreateProgramObjectARB = dlsym (RTLD_DEFAULT, "glCreateProgramObjectARB");
	glCreateShaderObjectARB = dlsym (RTLD_DEFAULT, "glCreateShaderObjectARB");
	glGetHandleARB = dlsym (RTLD_DEFAULT, "glGetHandleARB");
	glGetAttribLocationARB = dlsym (RTLD_DEFAULT, "glGetAttribLocationARB");
	glGetFragDataLocationEXT = dlsym (RTLD_DEFAULT, "glGetFragDataLocationEXT");
	glGetUniformBufferSizeEXT = dlsym (RTLD_DEFAULT, "glGetUniformBufferSizeEXT");
	glGetUniformLocationARB = dlsym (RTLD_DEFAULT, "glGetUniformLocationARB");
	glGetUniformOffsetEXT = dlsym (RTLD_DEFAULT, "glGetUniformOffsetEXT");
	glBindLightParameterEXT = dlsym (RTLD_DEFAULT, "glBindLightParameterEXT");
	glBindMaterialParameterEXT = dlsym (RTLD_DEFAULT, "glBindMaterialParameterEXT");
	glBindParameterEXT = dlsym (RTLD_DEFAULT, "glBindParameterEXT");
	glBindTexGenParameterEXT = dlsym (RTLD_DEFAULT, "glBindTexGenParameterEXT");
	glBindTextureUnitParameterEXT = dlsym (RTLD_DEFAULT, "glBindTextureUnitParameterEXT");
	glGenSymbolsEXT = dlsym (RTLD_DEFAULT, "glGenSymbolsEXT");
	glGenVertexShadersEXT = dlsym (RTLD_DEFAULT, "glGenVertexShadersEXT");
	glMapBufferARB = dlsym (RTLD_DEFAULT, "glMapBufferARB");
	glMapNamedBufferEXT = dlsym (RTLD_DEFAULT, "glMapNamedBufferEXT");
	glActiveStencilFaceEXT = dlsym (RTLD_DEFAULT, "glActiveStencilFaceEXT");
	glActiveTextureARB = dlsym (RTLD_DEFAULT, "glActiveTextureARB");
	glApplyTextureEXT = dlsym (RTLD_DEFAULT, "glApplyTextureEXT");
	glArrayElementEXT = dlsym (RTLD_DEFAULT, "glArrayElementEXT");
	glAttachObjectARB = dlsym (RTLD_DEFAULT, "glAttachObjectARB");
	glBeginQueryARB = dlsym (RTLD_DEFAULT, "glBeginQueryARB");
	glBeginTransformFeedbackEXT = dlsym (RTLD_DEFAULT, "glBeginTransformFeedbackEXT");
	glBeginVertexShaderEXT = dlsym (RTLD_DEFAULT, "glBeginVertexShaderEXT");
	glBindAttribLocationARB = dlsym (RTLD_DEFAULT, "glBindAttribLocationARB");
	glBindBufferARB = dlsym (RTLD_DEFAULT, "glBindBufferARB");
	glBindBufferBaseEXT = dlsym (RTLD_DEFAULT, "glBindBufferBaseEXT");
	glBindBufferOffsetEXT = dlsym (RTLD_DEFAULT, "glBindBufferOffsetEXT");
	glBindBufferRangeEXT = dlsym (RTLD_DEFAULT, "glBindBufferRangeEXT");
	glBindFragDataLocationEXT = dlsym (RTLD_DEFAULT, "glBindFragDataLocationEXT");
	glBindFramebufferEXT = dlsym (RTLD_DEFAULT, "glBindFramebufferEXT");
	glBindMultiTextureEXT = dlsym (RTLD_DEFAULT, "glBindMultiTextureEXT");
	glBindProgramARB = dlsym (RTLD_DEFAULT, "glBindProgramARB");
	glBindRenderbufferEXT = dlsym (RTLD_DEFAULT, "glBindRenderbufferEXT");
	glBindTextureEXT = dlsym (RTLD_DEFAULT, "glBindTextureEXT");
	glBindVertexShaderEXT = dlsym (RTLD_DEFAULT, "glBindVertexShaderEXT");
	glBinormal3bEXT = dlsym (RTLD_DEFAULT, "glBinormal3bEXT");
	glBinormal3bvEXT = dlsym (RTLD_DEFAULT, "glBinormal3bvEXT");
	glBinormal3dEXT = dlsym (RTLD_DEFAULT, "glBinormal3dEXT");
	glBinormal3dvEXT = dlsym (RTLD_DEFAULT, "glBinormal3dvEXT");
	glBinormal3fEXT = dlsym (RTLD_DEFAULT, "glBinormal3fEXT");
	glBinormal3fvEXT = dlsym (RTLD_DEFAULT, "glBinormal3fvEXT");
	glBinormal3iEXT = dlsym (RTLD_DEFAULT, "glBinormal3iEXT");
	glBinormal3ivEXT = dlsym (RTLD_DEFAULT, "glBinormal3ivEXT");
	glBinormal3sEXT = dlsym (RTLD_DEFAULT, "glBinormal3sEXT");
	glBinormal3svEXT = dlsym (RTLD_DEFAULT, "glBinormal3svEXT");
	glBinormalPointerEXT = dlsym (RTLD_DEFAULT, "glBinormalPointerEXT");
	glBlendColorEXT = dlsym (RTLD_DEFAULT, "glBlendColorEXT");
	glBlendEquationEXT = dlsym (RTLD_DEFAULT, "glBlendEquationEXT");
	glBlendEquationSeparateEXT = dlsym (RTLD_DEFAULT, "glBlendEquationSeparateEXT");
	glBlendFuncSeparateEXT = dlsym (RTLD_DEFAULT, "glBlendFuncSeparateEXT");
	glBlitFramebufferEXT = dlsym (RTLD_DEFAULT, "glBlitFramebufferEXT");
	glBufferDataARB = dlsym (RTLD_DEFAULT, "glBufferDataARB");
	glBufferSubDataARB = dlsym (RTLD_DEFAULT, "glBufferSubDataARB");
	glClampColorARB = dlsym (RTLD_DEFAULT, "glClampColorARB");
	glClearColorIiEXT = dlsym (RTLD_DEFAULT, "glClearColorIiEXT");
	glClearColorIuiEXT = dlsym (RTLD_DEFAULT, "glClearColorIuiEXT");
	glClientActiveTextureARB = dlsym (RTLD_DEFAULT, "glClientActiveTextureARB");
	glClientAttribDefaultEXT = dlsym (RTLD_DEFAULT, "glClientAttribDefaultEXT");
	glColorMaskIndexedEXT = dlsym (RTLD_DEFAULT, "glColorMaskIndexedEXT");
	glColorPointerEXT = dlsym (RTLD_DEFAULT, "glColorPointerEXT");
	glColorSubTableEXT = dlsym (RTLD_DEFAULT, "glColorSubTableEXT");
	glColorTableEXT = dlsym (RTLD_DEFAULT, "glColorTableEXT");
	glCompileShaderARB = dlsym (RTLD_DEFAULT, "glCompileShaderARB");
	glCompressedMultiTexImage1DEXT = dlsym (RTLD_DEFAULT, "glCompressedMultiTexImage1DEXT");
	glCompressedMultiTexImage2DEXT = dlsym (RTLD_DEFAULT, "glCompressedMultiTexImage2DEXT");
	glCompressedMultiTexImage3DEXT = dlsym (RTLD_DEFAULT, "glCompressedMultiTexImage3DEXT");
	glCompressedMultiTexSubImage1DEXT = dlsym (RTLD_DEFAULT, "glCompressedMultiTexSubImage1DEXT");
	glCompressedMultiTexSubImage2DEXT = dlsym (RTLD_DEFAULT, "glCompressedMultiTexSubImage2DEXT");
	glCompressedMultiTexSubImage3DEXT = dlsym (RTLD_DEFAULT, "glCompressedMultiTexSubImage3DEXT");
	glCompressedTexImage1DARB = dlsym (RTLD_DEFAULT, "glCompressedTexImage1DARB");
	glCompressedTexImage2DARB = dlsym (RTLD_DEFAULT, "glCompressedTexImage2DARB");
	glCompressedTexImage3DARB = dlsym (RTLD_DEFAULT, "glCompressedTexImage3DARB");
	glCompressedTexSubImage1DARB = dlsym (RTLD_DEFAULT, "glCompressedTexSubImage1DARB");
	glCompressedTexSubImage2DARB = dlsym (RTLD_DEFAULT, "glCompressedTexSubImage2DARB");
	glCompressedTexSubImage3DARB = dlsym (RTLD_DEFAULT, "glCompressedTexSubImage3DARB");
	glCompressedTextureImage1DEXT = dlsym (RTLD_DEFAULT, "glCompressedTextureImage1DEXT");
	glCompressedTextureImage2DEXT = dlsym (RTLD_DEFAULT, "glCompressedTextureImage2DEXT");
	glCompressedTextureImage3DEXT = dlsym (RTLD_DEFAULT, "glCompressedTextureImage3DEXT");
	glCompressedTextureSubImage1DEXT = dlsym (RTLD_DEFAULT, "glCompressedTextureSubImage1DEXT");
	glCompressedTextureSubImage2DEXT = dlsym (RTLD_DEFAULT, "glCompressedTextureSubImage2DEXT");
	glCompressedTextureSubImage3DEXT = dlsym (RTLD_DEFAULT, "glCompressedTextureSubImage3DEXT");
	glConvolutionFilter1DEXT = dlsym (RTLD_DEFAULT, "glConvolutionFilter1DEXT");
	glConvolutionFilter2DEXT = dlsym (RTLD_DEFAULT, "glConvolutionFilter2DEXT");
	glConvolutionParameterfEXT = dlsym (RTLD_DEFAULT, "glConvolutionParameterfEXT");
	glConvolutionParameterfvEXT = dlsym (RTLD_DEFAULT, "glConvolutionParameterfvEXT");
	glConvolutionParameteriEXT = dlsym (RTLD_DEFAULT, "glConvolutionParameteriEXT");
	glConvolutionParameterivEXT = dlsym (RTLD_DEFAULT, "glConvolutionParameterivEXT");
	glCopyColorSubTableEXT = dlsym (RTLD_DEFAULT, "glCopyColorSubTableEXT");
	glCopyConvolutionFilter1DEXT = dlsym (RTLD_DEFAULT, "glCopyConvolutionFilter1DEXT");
	glCopyConvolutionFilter2DEXT = dlsym (RTLD_DEFAULT, "glCopyConvolutionFilter2DEXT");
	glCopyMultiTexImage1DEXT = dlsym (RTLD_DEFAULT, "glCopyMultiTexImage1DEXT");
	glCopyMultiTexImage2DEXT = dlsym (RTLD_DEFAULT, "glCopyMultiTexImage2DEXT");
	glCopyMultiTexSubImage1DEXT = dlsym (RTLD_DEFAULT, "glCopyMultiTexSubImage1DEXT");
	glCopyMultiTexSubImage2DEXT = dlsym (RTLD_DEFAULT, "glCopyMultiTexSubImage2DEXT");
	glCopyMultiTexSubImage3DEXT = dlsym (RTLD_DEFAULT, "glCopyMultiTexSubImage3DEXT");
	glCopyTexImage1DEXT = dlsym (RTLD_DEFAULT, "glCopyTexImage1DEXT");
	glCopyTexImage2DEXT = dlsym (RTLD_DEFAULT, "glCopyTexImage2DEXT");
	glCopyTexSubImage1DEXT = dlsym (RTLD_DEFAULT, "glCopyTexSubImage1DEXT");
	glCopyTexSubImage2DEXT = dlsym (RTLD_DEFAULT, "glCopyTexSubImage2DEXT");
	glCopyTexSubImage3DEXT = dlsym (RTLD_DEFAULT, "glCopyTexSubImage3DEXT");
	glCopyTextureImage1DEXT = dlsym (RTLD_DEFAULT, "glCopyTextureImage1DEXT");
	glCopyTextureImage2DEXT = dlsym (RTLD_DEFAULT, "glCopyTextureImage2DEXT");
	glCopyTextureSubImage1DEXT = dlsym (RTLD_DEFAULT, "glCopyTextureSubImage1DEXT");
	glCopyTextureSubImage2DEXT = dlsym (RTLD_DEFAULT, "glCopyTextureSubImage2DEXT");
	glCopyTextureSubImage3DEXT = dlsym (RTLD_DEFAULT, "glCopyTextureSubImage3DEXT");
	glCullParameterdvEXT = dlsym (RTLD_DEFAULT, "glCullParameterdvEXT");
	glCullParameterfvEXT = dlsym (RTLD_DEFAULT, "glCullParameterfvEXT");
	glCurrentPaletteMatrixARB = dlsym (RTLD_DEFAULT, "glCurrentPaletteMatrixARB");
	glDeleteBuffersARB = dlsym (RTLD_DEFAULT, "glDeleteBuffersARB");
	glDeleteFramebuffersEXT = dlsym (RTLD_DEFAULT, "glDeleteFramebuffersEXT");
	glDeleteObjectARB = dlsym (RTLD_DEFAULT, "glDeleteObjectARB");
	glDeleteProgramsARB = dlsym (RTLD_DEFAULT, "glDeleteProgramsARB");
	glDeleteQueriesARB = dlsym (RTLD_DEFAULT, "glDeleteQueriesARB");
	glDeleteRenderbuffersEXT = dlsym (RTLD_DEFAULT, "glDeleteRenderbuffersEXT");
	glDeleteTexturesEXT = dlsym (RTLD_DEFAULT, "glDeleteTexturesEXT");
	glDeleteVertexShaderEXT = dlsym (RTLD_DEFAULT, "glDeleteVertexShaderEXT");
	glDepthBoundsEXT = dlsym (RTLD_DEFAULT, "glDepthBoundsEXT");
	glDetachObjectARB = dlsym (RTLD_DEFAULT, "glDetachObjectARB");
	glDisableClientStateIndexedEXT = dlsym (RTLD_DEFAULT, "glDisableClientStateIndexedEXT");
	glDisableIndexedEXT = dlsym (RTLD_DEFAULT, "glDisableIndexedEXT");
	glDisableVariantClientStateEXT = dlsym (RTLD_DEFAULT, "glDisableVariantClientStateEXT");
	glDisableVertexAttribArrayARB = dlsym (RTLD_DEFAULT, "glDisableVertexAttribArrayARB");
	glDrawArraysEXT = dlsym (RTLD_DEFAULT, "glDrawArraysEXT");
	glDrawArraysInstancedARB = dlsym (RTLD_DEFAULT, "glDrawArraysInstancedARB");
	glDrawArraysInstancedEXT = dlsym (RTLD_DEFAULT, "glDrawArraysInstancedEXT");
	glDrawBuffersARB = dlsym (RTLD_DEFAULT, "glDrawBuffersARB");
	glDrawElementsInstancedARB = dlsym (RTLD_DEFAULT, "glDrawElementsInstancedARB");
	glDrawElementsInstancedEXT = dlsym (RTLD_DEFAULT, "glDrawElementsInstancedEXT");
	glDrawRangeElementsEXT = dlsym (RTLD_DEFAULT, "glDrawRangeElementsEXT");
	glEdgeFlagPointerEXT = dlsym (RTLD_DEFAULT, "glEdgeFlagPointerEXT");
	glEnableClientStateIndexedEXT = dlsym (RTLD_DEFAULT, "glEnableClientStateIndexedEXT");
	glEnableIndexedEXT = dlsym (RTLD_DEFAULT, "glEnableIndexedEXT");
	glEnableVariantClientStateEXT = dlsym (RTLD_DEFAULT, "glEnableVariantClientStateEXT");
	glEnableVertexAttribArrayARB = dlsym (RTLD_DEFAULT, "glEnableVertexAttribArrayARB");
	glEndQueryARB = dlsym (RTLD_DEFAULT, "glEndQueryARB");
	glEndTransformFeedbackEXT = dlsym (RTLD_DEFAULT, "glEndTransformFeedbackEXT");
	glEndVertexShaderEXT = dlsym (RTLD_DEFAULT, "glEndVertexShaderEXT");
	glExtractComponentEXT = dlsym (RTLD_DEFAULT, "glExtractComponentEXT");
	glFogCoordPointerEXT = dlsym (RTLD_DEFAULT, "glFogCoordPointerEXT");
	glFogCoorddEXT = dlsym (RTLD_DEFAULT, "glFogCoorddEXT");
	glFogCoorddvEXT = dlsym (RTLD_DEFAULT, "glFogCoorddvEXT");
	glFogCoordfEXT = dlsym (RTLD_DEFAULT, "glFogCoordfEXT");
	glFogCoordfvEXT = dlsym (RTLD_DEFAULT, "glFogCoordfvEXT");
	glFramebufferDrawBufferEXT = dlsym (RTLD_DEFAULT, "glFramebufferDrawBufferEXT");
	glFramebufferDrawBuffersEXT = dlsym (RTLD_DEFAULT, "glFramebufferDrawBuffersEXT");
	glFramebufferReadBufferEXT = dlsym (RTLD_DEFAULT, "glFramebufferReadBufferEXT");
	glFramebufferRenderbufferEXT = dlsym (RTLD_DEFAULT, "glFramebufferRenderbufferEXT");
	glFramebufferTexture1DEXT = dlsym (RTLD_DEFAULT, "glFramebufferTexture1DEXT");
	glFramebufferTexture2DEXT = dlsym (RTLD_DEFAULT, "glFramebufferTexture2DEXT");
	glFramebufferTexture3DEXT = dlsym (RTLD_DEFAULT, "glFramebufferTexture3DEXT");
	glFramebufferTextureARB = dlsym (RTLD_DEFAULT, "glFramebufferTextureARB");
	glFramebufferTextureEXT = dlsym (RTLD_DEFAULT, "glFramebufferTextureEXT");
	glFramebufferTextureFaceARB = dlsym (RTLD_DEFAULT, "glFramebufferTextureFaceARB");
	glFramebufferTextureFaceEXT = dlsym (RTLD_DEFAULT, "glFramebufferTextureFaceEXT");
	glFramebufferTextureLayerARB = dlsym (RTLD_DEFAULT, "glFramebufferTextureLayerARB");
	glFramebufferTextureLayerEXT = dlsym (RTLD_DEFAULT, "glFramebufferTextureLayerEXT");
	glGenBuffersARB = dlsym (RTLD_DEFAULT, "glGenBuffersARB");
	glGenFramebuffersEXT = dlsym (RTLD_DEFAULT, "glGenFramebuffersEXT");
	glGenProgramsARB = dlsym (RTLD_DEFAULT, "glGenProgramsARB");
	glGenQueriesARB = dlsym (RTLD_DEFAULT, "glGenQueriesARB");
	glGenRenderbuffersEXT = dlsym (RTLD_DEFAULT, "glGenRenderbuffersEXT");
	glGenTexturesEXT = dlsym (RTLD_DEFAULT, "glGenTexturesEXT");
	glGenerateMipmapEXT = dlsym (RTLD_DEFAULT, "glGenerateMipmapEXT");
	glGenerateMultiTexMipmapEXT = dlsym (RTLD_DEFAULT, "glGenerateMultiTexMipmapEXT");
	glGenerateTextureMipmapEXT = dlsym (RTLD_DEFAULT, "glGenerateTextureMipmapEXT");
	glGetActiveAttribARB = dlsym (RTLD_DEFAULT, "glGetActiveAttribARB");
	glGetActiveUniformARB = dlsym (RTLD_DEFAULT, "glGetActiveUniformARB");
	glGetAttachedObjectsARB = dlsym (RTLD_DEFAULT, "glGetAttachedObjectsARB");
	glGetBooleanIndexedvEXT = dlsym (RTLD_DEFAULT, "glGetBooleanIndexedvEXT");
	glGetBufferParameterivARB = dlsym (RTLD_DEFAULT, "glGetBufferParameterivARB");
	glGetBufferPointervARB = dlsym (RTLD_DEFAULT, "glGetBufferPointervARB");
	glGetBufferSubDataARB = dlsym (RTLD_DEFAULT, "glGetBufferSubDataARB");
	glGetColorTableEXT = dlsym (RTLD_DEFAULT, "glGetColorTableEXT");
	glGetColorTableParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetColorTableParameterfvEXT");
	glGetColorTableParameterivEXT = dlsym (RTLD_DEFAULT, "glGetColorTableParameterivEXT");
	glGetCompressedMultiTexImageEXT = dlsym (RTLD_DEFAULT, "glGetCompressedMultiTexImageEXT");
	glGetCompressedTexImageARB = dlsym (RTLD_DEFAULT, "glGetCompressedTexImageARB");
	glGetCompressedTextureImageEXT = dlsym (RTLD_DEFAULT, "glGetCompressedTextureImageEXT");
	glGetConvolutionFilterEXT = dlsym (RTLD_DEFAULT, "glGetConvolutionFilterEXT");
	glGetConvolutionParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetConvolutionParameterfvEXT");
	glGetConvolutionParameterivEXT = dlsym (RTLD_DEFAULT, "glGetConvolutionParameterivEXT");
	glGetDoubleIndexedvEXT = dlsym (RTLD_DEFAULT, "glGetDoubleIndexedvEXT");
	glGetFloatIndexedvEXT = dlsym (RTLD_DEFAULT, "glGetFloatIndexedvEXT");
	glGetFramebufferAttachmentParameterivEXT = dlsym (RTLD_DEFAULT, "glGetFramebufferAttachmentParameterivEXT");
	glGetFramebufferParameterivEXT = dlsym (RTLD_DEFAULT, "glGetFramebufferParameterivEXT");
	glGetHistogramEXT = dlsym (RTLD_DEFAULT, "glGetHistogramEXT");
	glGetHistogramParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetHistogramParameterfvEXT");
	glGetHistogramParameterivEXT = dlsym (RTLD_DEFAULT, "glGetHistogramParameterivEXT");
	glGetInfoLogARB = dlsym (RTLD_DEFAULT, "glGetInfoLogARB");
	glGetIntegerIndexedvEXT = dlsym (RTLD_DEFAULT, "glGetIntegerIndexedvEXT");
	glGetInvariantBooleanvEXT = dlsym (RTLD_DEFAULT, "glGetInvariantBooleanvEXT");
	glGetInvariantFloatvEXT = dlsym (RTLD_DEFAULT, "glGetInvariantFloatvEXT");
	glGetInvariantIntegervEXT = dlsym (RTLD_DEFAULT, "glGetInvariantIntegervEXT");
	glGetLocalConstantBooleanvEXT = dlsym (RTLD_DEFAULT, "glGetLocalConstantBooleanvEXT");
	glGetLocalConstantFloatvEXT = dlsym (RTLD_DEFAULT, "glGetLocalConstantFloatvEXT");
	glGetLocalConstantIntegervEXT = dlsym (RTLD_DEFAULT, "glGetLocalConstantIntegervEXT");
	glGetMinmaxEXT = dlsym (RTLD_DEFAULT, "glGetMinmaxEXT");
	glGetMinmaxParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetMinmaxParameterfvEXT");
	glGetMinmaxParameterivEXT = dlsym (RTLD_DEFAULT, "glGetMinmaxParameterivEXT");
	glGetMultiTexEnvfvEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexEnvfvEXT");
	glGetMultiTexEnvivEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexEnvivEXT");
	glGetMultiTexGendvEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexGendvEXT");
	glGetMultiTexGenfvEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexGenfvEXT");
	glGetMultiTexGenivEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexGenivEXT");
	glGetMultiTexImageEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexImageEXT");
	glGetMultiTexLevelParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexLevelParameterfvEXT");
	glGetMultiTexLevelParameterivEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexLevelParameterivEXT");
	glGetMultiTexParameterIivEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexParameterIivEXT");
	glGetMultiTexParameterIuivEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexParameterIuivEXT");
	glGetMultiTexParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexParameterfvEXT");
	glGetMultiTexParameterivEXT = dlsym (RTLD_DEFAULT, "glGetMultiTexParameterivEXT");
	glGetNamedBufferParameterivEXT = dlsym (RTLD_DEFAULT, "glGetNamedBufferParameterivEXT");
	glGetNamedBufferPointervEXT = dlsym (RTLD_DEFAULT, "glGetNamedBufferPointervEXT");
	glGetNamedBufferSubDataEXT = dlsym (RTLD_DEFAULT, "glGetNamedBufferSubDataEXT");
	glGetNamedFramebufferAttachmentParameterivEXT = dlsym (RTLD_DEFAULT, "glGetNamedFramebufferAttachmentParameterivEXT");
	glGetNamedProgramLocalParameterIivEXT = dlsym (RTLD_DEFAULT, "glGetNamedProgramLocalParameterIivEXT");
	glGetNamedProgramLocalParameterIuivEXT = dlsym (RTLD_DEFAULT, "glGetNamedProgramLocalParameterIuivEXT");
	glGetNamedProgramLocalParameterdvEXT = dlsym (RTLD_DEFAULT, "glGetNamedProgramLocalParameterdvEXT");
	glGetNamedProgramLocalParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetNamedProgramLocalParameterfvEXT");
	glGetNamedProgramStringEXT = dlsym (RTLD_DEFAULT, "glGetNamedProgramStringEXT");
	glGetNamedProgramivEXT = dlsym (RTLD_DEFAULT, "glGetNamedProgramivEXT");
	glGetNamedRenderbufferParameterivEXT = dlsym (RTLD_DEFAULT, "glGetNamedRenderbufferParameterivEXT");
	glGetObjectParameterfvARB = dlsym (RTLD_DEFAULT, "glGetObjectParameterfvARB");
	glGetObjectParameterivARB = dlsym (RTLD_DEFAULT, "glGetObjectParameterivARB");
	glGetPointerIndexedvEXT = dlsym (RTLD_DEFAULT, "glGetPointerIndexedvEXT");
	glGetPointervEXT = dlsym (RTLD_DEFAULT, "glGetPointervEXT");
	glGetProgramEnvParameterdvARB = dlsym (RTLD_DEFAULT, "glGetProgramEnvParameterdvARB");
	glGetProgramEnvParameterfvARB = dlsym (RTLD_DEFAULT, "glGetProgramEnvParameterfvARB");
	glGetProgramLocalParameterdvARB = dlsym (RTLD_DEFAULT, "glGetProgramLocalParameterdvARB");
	glGetProgramLocalParameterfvARB = dlsym (RTLD_DEFAULT, "glGetProgramLocalParameterfvARB");
	glGetProgramStringARB = dlsym (RTLD_DEFAULT, "glGetProgramStringARB");
	glGetProgramivARB = dlsym (RTLD_DEFAULT, "glGetProgramivARB");
	glGetQueryObjecti64vEXT = dlsym (RTLD_DEFAULT, "glGetQueryObjecti64vEXT");
	glGetQueryObjectivARB = dlsym (RTLD_DEFAULT, "glGetQueryObjectivARB");
	glGetQueryObjectui64vEXT = dlsym (RTLD_DEFAULT, "glGetQueryObjectui64vEXT");
	glGetQueryObjectuivARB = dlsym (RTLD_DEFAULT, "glGetQueryObjectuivARB");
	glGetQueryivARB = dlsym (RTLD_DEFAULT, "glGetQueryivARB");
	glGetRenderbufferParameterivEXT = dlsym (RTLD_DEFAULT, "glGetRenderbufferParameterivEXT");
	glGetSeparableFilterEXT = dlsym (RTLD_DEFAULT, "glGetSeparableFilterEXT");
	glGetShaderSourceARB = dlsym (RTLD_DEFAULT, "glGetShaderSourceARB");
	glGetTexParameterIivEXT = dlsym (RTLD_DEFAULT, "glGetTexParameterIivEXT");
	glGetTexParameterIuivEXT = dlsym (RTLD_DEFAULT, "glGetTexParameterIuivEXT");
	glGetTextureImageEXT = dlsym (RTLD_DEFAULT, "glGetTextureImageEXT");
	glGetTextureLevelParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetTextureLevelParameterfvEXT");
	glGetTextureLevelParameterivEXT = dlsym (RTLD_DEFAULT, "glGetTextureLevelParameterivEXT");
	glGetTextureParameterIivEXT = dlsym (RTLD_DEFAULT, "glGetTextureParameterIivEXT");
	glGetTextureParameterIuivEXT = dlsym (RTLD_DEFAULT, "glGetTextureParameterIuivEXT");
	glGetTextureParameterfvEXT = dlsym (RTLD_DEFAULT, "glGetTextureParameterfvEXT");
	glGetTextureParameterivEXT = dlsym (RTLD_DEFAULT, "glGetTextureParameterivEXT");
	glGetTransformFeedbackVaryingEXT = dlsym (RTLD_DEFAULT, "glGetTransformFeedbackVaryingEXT");
	glGetUniformfvARB = dlsym (RTLD_DEFAULT, "glGetUniformfvARB");
	glGetUniformivARB = dlsym (RTLD_DEFAULT, "glGetUniformivARB");
	glGetUniformuivEXT = dlsym (RTLD_DEFAULT, "glGetUniformuivEXT");
	glGetVariantBooleanvEXT = dlsym (RTLD_DEFAULT, "glGetVariantBooleanvEXT");
	glGetVariantFloatvEXT = dlsym (RTLD_DEFAULT, "glGetVariantFloatvEXT");
	glGetVariantIntegervEXT = dlsym (RTLD_DEFAULT, "glGetVariantIntegervEXT");
	glGetVariantPointervEXT = dlsym (RTLD_DEFAULT, "glGetVariantPointervEXT");
	glGetVertexAttribIivEXT = dlsym (RTLD_DEFAULT, "glGetVertexAttribIivEXT");
	glGetVertexAttribIuivEXT = dlsym (RTLD_DEFAULT, "glGetVertexAttribIuivEXT");
	glGetVertexAttribPointervARB = dlsym (RTLD_DEFAULT, "glGetVertexAttribPointervARB");
	glGetVertexAttribdvARB = dlsym (RTLD_DEFAULT, "glGetVertexAttribdvARB");
	glGetVertexAttribfvARB = dlsym (RTLD_DEFAULT, "glGetVertexAttribfvARB");
	glGetVertexAttribivARB = dlsym (RTLD_DEFAULT, "glGetVertexAttribivARB");
	glHistogramEXT = dlsym (RTLD_DEFAULT, "glHistogramEXT");
	glIndexFuncEXT = dlsym (RTLD_DEFAULT, "glIndexFuncEXT");
	glIndexMaterialEXT = dlsym (RTLD_DEFAULT, "glIndexMaterialEXT");
	glIndexPointerEXT = dlsym (RTLD_DEFAULT, "glIndexPointerEXT");
	glInsertComponentEXT = dlsym (RTLD_DEFAULT, "glInsertComponentEXT");
	glLinkProgramARB = dlsym (RTLD_DEFAULT, "glLinkProgramARB");
	glLoadTransposeMatrixdARB = dlsym (RTLD_DEFAULT, "glLoadTransposeMatrixdARB");
	glLoadTransposeMatrixfARB = dlsym (RTLD_DEFAULT, "glLoadTransposeMatrixfARB");
	glLockArraysEXT = dlsym (RTLD_DEFAULT, "glLockArraysEXT");
	glMatrixFrustumEXT = dlsym (RTLD_DEFAULT, "glMatrixFrustumEXT");
	glMatrixIndexPointerARB = dlsym (RTLD_DEFAULT, "glMatrixIndexPointerARB");
	glMatrixIndexubvARB = dlsym (RTLD_DEFAULT, "glMatrixIndexubvARB");
	glMatrixIndexuivARB = dlsym (RTLD_DEFAULT, "glMatrixIndexuivARB");
	glMatrixIndexusvARB = dlsym (RTLD_DEFAULT, "glMatrixIndexusvARB");
	glMatrixLoadIdentityEXT = dlsym (RTLD_DEFAULT, "glMatrixLoadIdentityEXT");
	glMatrixLoadTransposedEXT = dlsym (RTLD_DEFAULT, "glMatrixLoadTransposedEXT");
	glMatrixLoadTransposefEXT = dlsym (RTLD_DEFAULT, "glMatrixLoadTransposefEXT");
	glMatrixLoaddEXT = dlsym (RTLD_DEFAULT, "glMatrixLoaddEXT");
	glMatrixLoadfEXT = dlsym (RTLD_DEFAULT, "glMatrixLoadfEXT");
	glMatrixMultTransposedEXT = dlsym (RTLD_DEFAULT, "glMatrixMultTransposedEXT");
	glMatrixMultTransposefEXT = dlsym (RTLD_DEFAULT, "glMatrixMultTransposefEXT");
	glMatrixMultdEXT = dlsym (RTLD_DEFAULT, "glMatrixMultdEXT");
	glMatrixMultfEXT = dlsym (RTLD_DEFAULT, "glMatrixMultfEXT");
	glMatrixOrthoEXT = dlsym (RTLD_DEFAULT, "glMatrixOrthoEXT");
	glMatrixPopEXT = dlsym (RTLD_DEFAULT, "glMatrixPopEXT");
	glMatrixPushEXT = dlsym (RTLD_DEFAULT, "glMatrixPushEXT");
	glMatrixRotatedEXT = dlsym (RTLD_DEFAULT, "glMatrixRotatedEXT");
	glMatrixRotatefEXT = dlsym (RTLD_DEFAULT, "glMatrixRotatefEXT");
	glMatrixScaledEXT = dlsym (RTLD_DEFAULT, "glMatrixScaledEXT");
	glMatrixScalefEXT = dlsym (RTLD_DEFAULT, "glMatrixScalefEXT");
	glMatrixTranslatedEXT = dlsym (RTLD_DEFAULT, "glMatrixTranslatedEXT");
	glMatrixTranslatefEXT = dlsym (RTLD_DEFAULT, "glMatrixTranslatefEXT");
	glMinmaxEXT = dlsym (RTLD_DEFAULT, "glMinmaxEXT");
	glMultTransposeMatrixdARB = dlsym (RTLD_DEFAULT, "glMultTransposeMatrixdARB");
	glMultTransposeMatrixfARB = dlsym (RTLD_DEFAULT, "glMultTransposeMatrixfARB");
	glMultiDrawArraysEXT = dlsym (RTLD_DEFAULT, "glMultiDrawArraysEXT");
	glMultiDrawElementsEXT = dlsym (RTLD_DEFAULT, "glMultiDrawElementsEXT");
	glMultiTexBufferEXT = dlsym (RTLD_DEFAULT, "glMultiTexBufferEXT");
	glMultiTexCoord1dARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1dARB");
	glMultiTexCoord1dvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1dvARB");
	glMultiTexCoord1fARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1fARB");
	glMultiTexCoord1fvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1fvARB");
	glMultiTexCoord1iARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1iARB");
	glMultiTexCoord1ivARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1ivARB");
	glMultiTexCoord1sARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1sARB");
	glMultiTexCoord1svARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord1svARB");
	glMultiTexCoord2dARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2dARB");
	glMultiTexCoord2dvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2dvARB");
	glMultiTexCoord2fARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2fARB");
	glMultiTexCoord2fvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2fvARB");
	glMultiTexCoord2iARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2iARB");
	glMultiTexCoord2ivARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2ivARB");
	glMultiTexCoord2sARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2sARB");
	glMultiTexCoord2svARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord2svARB");
	glMultiTexCoord3dARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3dARB");
	glMultiTexCoord3dvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3dvARB");
	glMultiTexCoord3fARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3fARB");
	glMultiTexCoord3fvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3fvARB");
	glMultiTexCoord3iARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3iARB");
	glMultiTexCoord3ivARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3ivARB");
	glMultiTexCoord3sARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3sARB");
	glMultiTexCoord3svARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord3svARB");
	glMultiTexCoord4dARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4dARB");
	glMultiTexCoord4dvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4dvARB");
	glMultiTexCoord4fARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4fARB");
	glMultiTexCoord4fvARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4fvARB");
	glMultiTexCoord4iARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4iARB");
	glMultiTexCoord4ivARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4ivARB");
	glMultiTexCoord4sARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4sARB");
	glMultiTexCoord4svARB = dlsym (RTLD_DEFAULT, "glMultiTexCoord4svARB");
	glMultiTexCoordPointerEXT = dlsym (RTLD_DEFAULT, "glMultiTexCoordPointerEXT");
	glMultiTexEnvfEXT = dlsym (RTLD_DEFAULT, "glMultiTexEnvfEXT");
	glMultiTexEnvfvEXT = dlsym (RTLD_DEFAULT, "glMultiTexEnvfvEXT");
	glMultiTexEnviEXT = dlsym (RTLD_DEFAULT, "glMultiTexEnviEXT");
	glMultiTexEnvivEXT = dlsym (RTLD_DEFAULT, "glMultiTexEnvivEXT");
	glMultiTexGendEXT = dlsym (RTLD_DEFAULT, "glMultiTexGendEXT");
	glMultiTexGendvEXT = dlsym (RTLD_DEFAULT, "glMultiTexGendvEXT");
	glMultiTexGenfEXT = dlsym (RTLD_DEFAULT, "glMultiTexGenfEXT");
	glMultiTexGenfvEXT = dlsym (RTLD_DEFAULT, "glMultiTexGenfvEXT");
	glMultiTexGeniEXT = dlsym (RTLD_DEFAULT, "glMultiTexGeniEXT");
	glMultiTexGenivEXT = dlsym (RTLD_DEFAULT, "glMultiTexGenivEXT");
	glMultiTexImage1DEXT = dlsym (RTLD_DEFAULT, "glMultiTexImage1DEXT");
	glMultiTexImage2DEXT = dlsym (RTLD_DEFAULT, "glMultiTexImage2DEXT");
	glMultiTexImage3DEXT = dlsym (RTLD_DEFAULT, "glMultiTexImage3DEXT");
	glMultiTexParameterIivEXT = dlsym (RTLD_DEFAULT, "glMultiTexParameterIivEXT");
	glMultiTexParameterIuivEXT = dlsym (RTLD_DEFAULT, "glMultiTexParameterIuivEXT");
	glMultiTexParameterfEXT = dlsym (RTLD_DEFAULT, "glMultiTexParameterfEXT");
	glMultiTexParameterfvEXT = dlsym (RTLD_DEFAULT, "glMultiTexParameterfvEXT");
	glMultiTexParameteriEXT = dlsym (RTLD_DEFAULT, "glMultiTexParameteriEXT");
	glMultiTexParameterivEXT = dlsym (RTLD_DEFAULT, "glMultiTexParameterivEXT");
	glMultiTexRenderbufferEXT = dlsym (RTLD_DEFAULT, "glMultiTexRenderbufferEXT");
	glMultiTexSubImage1DEXT = dlsym (RTLD_DEFAULT, "glMultiTexSubImage1DEXT");
	glMultiTexSubImage2DEXT = dlsym (RTLD_DEFAULT, "glMultiTexSubImage2DEXT");
	glMultiTexSubImage3DEXT = dlsym (RTLD_DEFAULT, "glMultiTexSubImage3DEXT");
	glNamedBufferDataEXT = dlsym (RTLD_DEFAULT, "glNamedBufferDataEXT");
	glNamedBufferSubDataEXT = dlsym (RTLD_DEFAULT, "glNamedBufferSubDataEXT");
	glNamedFramebufferRenderbufferEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferRenderbufferEXT");
	glNamedFramebufferTexture1DEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferTexture1DEXT");
	glNamedFramebufferTexture2DEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferTexture2DEXT");
	glNamedFramebufferTexture3DEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferTexture3DEXT");
	glNamedFramebufferTextureEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferTextureEXT");
	glNamedFramebufferTextureFaceEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferTextureFaceEXT");
	glNamedFramebufferTextureLayerEXT = dlsym (RTLD_DEFAULT, "glNamedFramebufferTextureLayerEXT");
	glNamedProgramLocalParameter4dEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameter4dEXT");
	glNamedProgramLocalParameter4dvEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameter4dvEXT");
	glNamedProgramLocalParameter4fEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameter4fEXT");
	glNamedProgramLocalParameter4fvEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameter4fvEXT");
	glNamedProgramLocalParameterI4iEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameterI4iEXT");
	glNamedProgramLocalParameterI4ivEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameterI4ivEXT");
	glNamedProgramLocalParameterI4uiEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameterI4uiEXT");
	glNamedProgramLocalParameterI4uivEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameterI4uivEXT");
	glNamedProgramLocalParameters4fvEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParameters4fvEXT");
	glNamedProgramLocalParametersI4ivEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParametersI4ivEXT");
	glNamedProgramLocalParametersI4uivEXT = dlsym (RTLD_DEFAULT, "glNamedProgramLocalParametersI4uivEXT");
	glNamedProgramStringEXT = dlsym (RTLD_DEFAULT, "glNamedProgramStringEXT");
	glNamedRenderbufferStorageEXT = dlsym (RTLD_DEFAULT, "glNamedRenderbufferStorageEXT");
	glNamedRenderbufferStorageMultisampleCoverageEXT = dlsym (RTLD_DEFAULT, "glNamedRenderbufferStorageMultisampleCoverageEXT");
	glNamedRenderbufferStorageMultisampleEXT = dlsym (RTLD_DEFAULT, "glNamedRenderbufferStorageMultisampleEXT");
	glNormalPointerEXT = dlsym (RTLD_DEFAULT, "glNormalPointerEXT");
	glPixelTransformParameterfEXT = dlsym (RTLD_DEFAULT, "glPixelTransformParameterfEXT");
	glPixelTransformParameterfvEXT = dlsym (RTLD_DEFAULT, "glPixelTransformParameterfvEXT");
	glPixelTransformParameteriEXT = dlsym (RTLD_DEFAULT, "glPixelTransformParameteriEXT");
	glPixelTransformParameterivEXT = dlsym (RTLD_DEFAULT, "glPixelTransformParameterivEXT");
	glPointParameterfARB = dlsym (RTLD_DEFAULT, "glPointParameterfARB");
	glPointParameterfEXT = dlsym (RTLD_DEFAULT, "glPointParameterfEXT");
	glPointParameterfvARB = dlsym (RTLD_DEFAULT, "glPointParameterfvARB");
	glPointParameterfvEXT = dlsym (RTLD_DEFAULT, "glPointParameterfvEXT");
	glPolygonOffsetEXT = dlsym (RTLD_DEFAULT, "glPolygonOffsetEXT");
	glPrioritizeTexturesEXT = dlsym (RTLD_DEFAULT, "glPrioritizeTexturesEXT");
	glProgramEnvParameter4dARB = dlsym (RTLD_DEFAULT, "glProgramEnvParameter4dARB");
	glProgramEnvParameter4dvARB = dlsym (RTLD_DEFAULT, "glProgramEnvParameter4dvARB");
	glProgramEnvParameter4fARB = dlsym (RTLD_DEFAULT, "glProgramEnvParameter4fARB");
	glProgramEnvParameter4fvARB = dlsym (RTLD_DEFAULT, "glProgramEnvParameter4fvARB");
	glProgramEnvParameters4fvEXT = dlsym (RTLD_DEFAULT, "glProgramEnvParameters4fvEXT");
	glProgramLocalParameter4dARB = dlsym (RTLD_DEFAULT, "glProgramLocalParameter4dARB");
	glProgramLocalParameter4dvARB = dlsym (RTLD_DEFAULT, "glProgramLocalParameter4dvARB");
	glProgramLocalParameter4fARB = dlsym (RTLD_DEFAULT, "glProgramLocalParameter4fARB");
	glProgramLocalParameter4fvARB = dlsym (RTLD_DEFAULT, "glProgramLocalParameter4fvARB");
	glProgramLocalParameters4fvEXT = dlsym (RTLD_DEFAULT, "glProgramLocalParameters4fvEXT");
	glProgramParameteriARB = dlsym (RTLD_DEFAULT, "glProgramParameteriARB");
	glProgramParameteriEXT = dlsym (RTLD_DEFAULT, "glProgramParameteriEXT");
	glProgramStringARB = dlsym (RTLD_DEFAULT, "glProgramStringARB");
	glProgramUniform1fEXT = dlsym (RTLD_DEFAULT, "glProgramUniform1fEXT");
	glProgramUniform1fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniform1fvEXT");
	glProgramUniform1iEXT = dlsym (RTLD_DEFAULT, "glProgramUniform1iEXT");
	glProgramUniform1ivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform1ivEXT");
	glProgramUniform1uiEXT = dlsym (RTLD_DEFAULT, "glProgramUniform1uiEXT");
	glProgramUniform1uivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform1uivEXT");
	glProgramUniform2fEXT = dlsym (RTLD_DEFAULT, "glProgramUniform2fEXT");
	glProgramUniform2fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniform2fvEXT");
	glProgramUniform2iEXT = dlsym (RTLD_DEFAULT, "glProgramUniform2iEXT");
	glProgramUniform2ivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform2ivEXT");
	glProgramUniform2uiEXT = dlsym (RTLD_DEFAULT, "glProgramUniform2uiEXT");
	glProgramUniform2uivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform2uivEXT");
	glProgramUniform3fEXT = dlsym (RTLD_DEFAULT, "glProgramUniform3fEXT");
	glProgramUniform3fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniform3fvEXT");
	glProgramUniform3iEXT = dlsym (RTLD_DEFAULT, "glProgramUniform3iEXT");
	glProgramUniform3ivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform3ivEXT");
	glProgramUniform3uiEXT = dlsym (RTLD_DEFAULT, "glProgramUniform3uiEXT");
	glProgramUniform3uivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform3uivEXT");
	glProgramUniform4fEXT = dlsym (RTLD_DEFAULT, "glProgramUniform4fEXT");
	glProgramUniform4fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniform4fvEXT");
	glProgramUniform4iEXT = dlsym (RTLD_DEFAULT, "glProgramUniform4iEXT");
	glProgramUniform4ivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform4ivEXT");
	glProgramUniform4uiEXT = dlsym (RTLD_DEFAULT, "glProgramUniform4uiEXT");
	glProgramUniform4uivEXT = dlsym (RTLD_DEFAULT, "glProgramUniform4uivEXT");
	glProgramUniformMatrix2fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix2fvEXT");
	glProgramUniformMatrix2x3fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix2x3fvEXT");
	glProgramUniformMatrix2x4fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix2x4fvEXT");
	glProgramUniformMatrix3fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix3fvEXT");
	glProgramUniformMatrix3x2fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix3x2fvEXT");
	glProgramUniformMatrix3x4fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix3x4fvEXT");
	glProgramUniformMatrix4fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix4fvEXT");
	glProgramUniformMatrix4x2fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix4x2fvEXT");
	glProgramUniformMatrix4x3fvEXT = dlsym (RTLD_DEFAULT, "glProgramUniformMatrix4x3fvEXT");
	glProvokingVertexEXT = dlsym (RTLD_DEFAULT, "glProvokingVertexEXT");
	glPushClientAttribDefaultEXT = dlsym (RTLD_DEFAULT, "glPushClientAttribDefaultEXT");
	glRenderbufferStorageEXT = dlsym (RTLD_DEFAULT, "glRenderbufferStorageEXT");
	glRenderbufferStorageMultisampleEXT = dlsym (RTLD_DEFAULT, "glRenderbufferStorageMultisampleEXT");
	glResetHistogramEXT = dlsym (RTLD_DEFAULT, "glResetHistogramEXT");
	glResetMinmaxEXT = dlsym (RTLD_DEFAULT, "glResetMinmaxEXT");
	glSampleCoverageARB = dlsym (RTLD_DEFAULT, "glSampleCoverageARB");
	glSampleMaskEXT = dlsym (RTLD_DEFAULT, "glSampleMaskEXT");
	glSamplePatternEXT = dlsym (RTLD_DEFAULT, "glSamplePatternEXT");
	glSecondaryColor3bEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3bEXT");
	glSecondaryColor3bvEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3bvEXT");
	glSecondaryColor3dEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3dEXT");
	glSecondaryColor3dvEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3dvEXT");
	glSecondaryColor3fEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3fEXT");
	glSecondaryColor3fvEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3fvEXT");
	glSecondaryColor3iEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3iEXT");
	glSecondaryColor3ivEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3ivEXT");
	glSecondaryColor3sEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3sEXT");
	glSecondaryColor3svEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3svEXT");
	glSecondaryColor3ubEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3ubEXT");
	glSecondaryColor3ubvEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3ubvEXT");
	glSecondaryColor3uiEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3uiEXT");
	glSecondaryColor3uivEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3uivEXT");
	glSecondaryColor3usEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3usEXT");
	glSecondaryColor3usvEXT = dlsym (RTLD_DEFAULT, "glSecondaryColor3usvEXT");
	glSecondaryColorPointerEXT = dlsym (RTLD_DEFAULT, "glSecondaryColorPointerEXT");
	glSeparableFilter2DEXT = dlsym (RTLD_DEFAULT, "glSeparableFilter2DEXT");
	glSetInvariantEXT = dlsym (RTLD_DEFAULT, "glSetInvariantEXT");
	glSetLocalConstantEXT = dlsym (RTLD_DEFAULT, "glSetLocalConstantEXT");
	glShaderOp1EXT = dlsym (RTLD_DEFAULT, "glShaderOp1EXT");
	glShaderOp2EXT = dlsym (RTLD_DEFAULT, "glShaderOp2EXT");
	glShaderOp3EXT = dlsym (RTLD_DEFAULT, "glShaderOp3EXT");
	glShaderSourceARB = dlsym (RTLD_DEFAULT, "glShaderSourceARB");
	glStencilClearTagEXT = dlsym (RTLD_DEFAULT, "glStencilClearTagEXT");
	glSwizzleEXT = dlsym (RTLD_DEFAULT, "glSwizzleEXT");
	glTangent3bEXT = dlsym (RTLD_DEFAULT, "glTangent3bEXT");
	glTangent3bvEXT = dlsym (RTLD_DEFAULT, "glTangent3bvEXT");
	glTangent3dEXT = dlsym (RTLD_DEFAULT, "glTangent3dEXT");
	glTangent3dvEXT = dlsym (RTLD_DEFAULT, "glTangent3dvEXT");
	glTangent3fEXT = dlsym (RTLD_DEFAULT, "glTangent3fEXT");
	glTangent3fvEXT = dlsym (RTLD_DEFAULT, "glTangent3fvEXT");
	glTangent3iEXT = dlsym (RTLD_DEFAULT, "glTangent3iEXT");
	glTangent3ivEXT = dlsym (RTLD_DEFAULT, "glTangent3ivEXT");
	glTangent3sEXT = dlsym (RTLD_DEFAULT, "glTangent3sEXT");
	glTangent3svEXT = dlsym (RTLD_DEFAULT, "glTangent3svEXT");
	glTangentPointerEXT = dlsym (RTLD_DEFAULT, "glTangentPointerEXT");
	glTexBufferARB = dlsym (RTLD_DEFAULT, "glTexBufferARB");
	glTexBufferEXT = dlsym (RTLD_DEFAULT, "glTexBufferEXT");
	glTexCoordPointerEXT = dlsym (RTLD_DEFAULT, "glTexCoordPointerEXT");
	glTexImage3DEXT = dlsym (RTLD_DEFAULT, "glTexImage3DEXT");
	glTexParameterIivEXT = dlsym (RTLD_DEFAULT, "glTexParameterIivEXT");
	glTexParameterIuivEXT = dlsym (RTLD_DEFAULT, "glTexParameterIuivEXT");
	glTexSubImage1DEXT = dlsym (RTLD_DEFAULT, "glTexSubImage1DEXT");
	glTexSubImage2DEXT = dlsym (RTLD_DEFAULT, "glTexSubImage2DEXT");
	glTexSubImage3DEXT = dlsym (RTLD_DEFAULT, "glTexSubImage3DEXT");
	glTextureBufferEXT = dlsym (RTLD_DEFAULT, "glTextureBufferEXT");
	glTextureImage1DEXT = dlsym (RTLD_DEFAULT, "glTextureImage1DEXT");
	glTextureImage2DEXT = dlsym (RTLD_DEFAULT, "glTextureImage2DEXT");
	glTextureImage3DEXT = dlsym (RTLD_DEFAULT, "glTextureImage3DEXT");
	glTextureLightEXT = dlsym (RTLD_DEFAULT, "glTextureLightEXT");
	glTextureMaterialEXT = dlsym (RTLD_DEFAULT, "glTextureMaterialEXT");
	glTextureNormalEXT = dlsym (RTLD_DEFAULT, "glTextureNormalEXT");
	glTextureParameterIivEXT = dlsym (RTLD_DEFAULT, "glTextureParameterIivEXT");
	glTextureParameterIuivEXT = dlsym (RTLD_DEFAULT, "glTextureParameterIuivEXT");
	glTextureParameterfEXT = dlsym (RTLD_DEFAULT, "glTextureParameterfEXT");
	glTextureParameterfvEXT = dlsym (RTLD_DEFAULT, "glTextureParameterfvEXT");
	glTextureParameteriEXT = dlsym (RTLD_DEFAULT, "glTextureParameteriEXT");
	glTextureParameterivEXT = dlsym (RTLD_DEFAULT, "glTextureParameterivEXT");
	glTextureRenderbufferEXT = dlsym (RTLD_DEFAULT, "glTextureRenderbufferEXT");
	glTextureSubImage1DEXT = dlsym (RTLD_DEFAULT, "glTextureSubImage1DEXT");
	glTextureSubImage2DEXT = dlsym (RTLD_DEFAULT, "glTextureSubImage2DEXT");
	glTextureSubImage3DEXT = dlsym (RTLD_DEFAULT, "glTextureSubImage3DEXT");
	glTransformFeedbackVaryingsEXT = dlsym (RTLD_DEFAULT, "glTransformFeedbackVaryingsEXT");
	glUniform1fARB = dlsym (RTLD_DEFAULT, "glUniform1fARB");
	glUniform1fvARB = dlsym (RTLD_DEFAULT, "glUniform1fvARB");
	glUniform1iARB = dlsym (RTLD_DEFAULT, "glUniform1iARB");
	glUniform1ivARB = dlsym (RTLD_DEFAULT, "glUniform1ivARB");
	glUniform1uiEXT = dlsym (RTLD_DEFAULT, "glUniform1uiEXT");
	glUniform1uivEXT = dlsym (RTLD_DEFAULT, "glUniform1uivEXT");
	glUniform2fARB = dlsym (RTLD_DEFAULT, "glUniform2fARB");
	glUniform2fvARB = dlsym (RTLD_DEFAULT, "glUniform2fvARB");
	glUniform2iARB = dlsym (RTLD_DEFAULT, "glUniform2iARB");
	glUniform2ivARB = dlsym (RTLD_DEFAULT, "glUniform2ivARB");
	glUniform2uiEXT = dlsym (RTLD_DEFAULT, "glUniform2uiEXT");
	glUniform2uivEXT = dlsym (RTLD_DEFAULT, "glUniform2uivEXT");
	glUniform3fARB = dlsym (RTLD_DEFAULT, "glUniform3fARB");
	glUniform3fvARB = dlsym (RTLD_DEFAULT, "glUniform3fvARB");
	glUniform3iARB = dlsym (RTLD_DEFAULT, "glUniform3iARB");
	glUniform3ivARB = dlsym (RTLD_DEFAULT, "glUniform3ivARB");
	glUniform3uiEXT = dlsym (RTLD_DEFAULT, "glUniform3uiEXT");
	glUniform3uivEXT = dlsym (RTLD_DEFAULT, "glUniform3uivEXT");
	glUniform4fARB = dlsym (RTLD_DEFAULT, "glUniform4fARB");
	glUniform4fvARB = dlsym (RTLD_DEFAULT, "glUniform4fvARB");
	glUniform4iARB = dlsym (RTLD_DEFAULT, "glUniform4iARB");
	glUniform4ivARB = dlsym (RTLD_DEFAULT, "glUniform4ivARB");
	glUniform4uiEXT = dlsym (RTLD_DEFAULT, "glUniform4uiEXT");
	glUniform4uivEXT = dlsym (RTLD_DEFAULT, "glUniform4uivEXT");
	glUniformBufferEXT = dlsym (RTLD_DEFAULT, "glUniformBufferEXT");
	glUniformMatrix2fvARB = dlsym (RTLD_DEFAULT, "glUniformMatrix2fvARB");
	glUniformMatrix3fvARB = dlsym (RTLD_DEFAULT, "glUniformMatrix3fvARB");
	glUniformMatrix4fvARB = dlsym (RTLD_DEFAULT, "glUniformMatrix4fvARB");
	glUnlockArraysEXT = dlsym (RTLD_DEFAULT, "glUnlockArraysEXT");
	glUseProgramObjectARB = dlsym (RTLD_DEFAULT, "glUseProgramObjectARB");
	glValidateProgramARB = dlsym (RTLD_DEFAULT, "glValidateProgramARB");
	glVariantPointerEXT = dlsym (RTLD_DEFAULT, "glVariantPointerEXT");
	glVariantbvEXT = dlsym (RTLD_DEFAULT, "glVariantbvEXT");
	glVariantdvEXT = dlsym (RTLD_DEFAULT, "glVariantdvEXT");
	glVariantfvEXT = dlsym (RTLD_DEFAULT, "glVariantfvEXT");
	glVariantivEXT = dlsym (RTLD_DEFAULT, "glVariantivEXT");
	glVariantsvEXT = dlsym (RTLD_DEFAULT, "glVariantsvEXT");
	glVariantubvEXT = dlsym (RTLD_DEFAULT, "glVariantubvEXT");
	glVariantuivEXT = dlsym (RTLD_DEFAULT, "glVariantuivEXT");
	glVariantusvEXT = dlsym (RTLD_DEFAULT, "glVariantusvEXT");
	glVertexAttrib1dARB = dlsym (RTLD_DEFAULT, "glVertexAttrib1dARB");
	glVertexAttrib1dvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib1dvARB");
	glVertexAttrib1fARB = dlsym (RTLD_DEFAULT, "glVertexAttrib1fARB");
	glVertexAttrib1fvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib1fvARB");
	glVertexAttrib1sARB = dlsym (RTLD_DEFAULT, "glVertexAttrib1sARB");
	glVertexAttrib1svARB = dlsym (RTLD_DEFAULT, "glVertexAttrib1svARB");
	glVertexAttrib2dARB = dlsym (RTLD_DEFAULT, "glVertexAttrib2dARB");
	glVertexAttrib2dvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib2dvARB");
	glVertexAttrib2fARB = dlsym (RTLD_DEFAULT, "glVertexAttrib2fARB");
	glVertexAttrib2fvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib2fvARB");
	glVertexAttrib2sARB = dlsym (RTLD_DEFAULT, "glVertexAttrib2sARB");
	glVertexAttrib2svARB = dlsym (RTLD_DEFAULT, "glVertexAttrib2svARB");
	glVertexAttrib3dARB = dlsym (RTLD_DEFAULT, "glVertexAttrib3dARB");
	glVertexAttrib3dvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib3dvARB");
	glVertexAttrib3fARB = dlsym (RTLD_DEFAULT, "glVertexAttrib3fARB");
	glVertexAttrib3fvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib3fvARB");
	glVertexAttrib3sARB = dlsym (RTLD_DEFAULT, "glVertexAttrib3sARB");
	glVertexAttrib3svARB = dlsym (RTLD_DEFAULT, "glVertexAttrib3svARB");
	glVertexAttrib4NbvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NbvARB");
	glVertexAttrib4NivARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NivARB");
	glVertexAttrib4NsvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NsvARB");
	glVertexAttrib4NubARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NubARB");
	glVertexAttrib4NubvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NubvARB");
	glVertexAttrib4NuivARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NuivARB");
	glVertexAttrib4NusvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4NusvARB");
	glVertexAttrib4bvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4bvARB");
	glVertexAttrib4dARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4dARB");
	glVertexAttrib4dvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4dvARB");
	glVertexAttrib4fARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4fARB");
	glVertexAttrib4fvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4fvARB");
	glVertexAttrib4ivARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4ivARB");
	glVertexAttrib4sARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4sARB");
	glVertexAttrib4svARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4svARB");
	glVertexAttrib4ubvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4ubvARB");
	glVertexAttrib4uivARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4uivARB");
	glVertexAttrib4usvARB = dlsym (RTLD_DEFAULT, "glVertexAttrib4usvARB");
	glVertexAttribI1iEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI1iEXT");
	glVertexAttribI1ivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI1ivEXT");
	glVertexAttribI1uiEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI1uiEXT");
	glVertexAttribI1uivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI1uivEXT");
	glVertexAttribI2iEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI2iEXT");
	glVertexAttribI2ivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI2ivEXT");
	glVertexAttribI2uiEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI2uiEXT");
	glVertexAttribI2uivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI2uivEXT");
	glVertexAttribI3iEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI3iEXT");
	glVertexAttribI3ivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI3ivEXT");
	glVertexAttribI3uiEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI3uiEXT");
	glVertexAttribI3uivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI3uivEXT");
	glVertexAttribI4bvEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4bvEXT");
	glVertexAttribI4iEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4iEXT");
	glVertexAttribI4ivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4ivEXT");
	glVertexAttribI4svEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4svEXT");
	glVertexAttribI4ubvEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4ubvEXT");
	glVertexAttribI4uiEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4uiEXT");
	glVertexAttribI4uivEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4uivEXT");
	glVertexAttribI4usvEXT = dlsym (RTLD_DEFAULT, "glVertexAttribI4usvEXT");
	glVertexAttribIPointerEXT = dlsym (RTLD_DEFAULT, "glVertexAttribIPointerEXT");
	glVertexAttribPointerARB = dlsym (RTLD_DEFAULT, "glVertexAttribPointerARB");
	glVertexBlendARB = dlsym (RTLD_DEFAULT, "glVertexBlendARB");
	glVertexPointerEXT = dlsym (RTLD_DEFAULT, "glVertexPointerEXT");
	glVertexWeightPointerEXT = dlsym (RTLD_DEFAULT, "glVertexWeightPointerEXT");
	glVertexWeightfEXT = dlsym (RTLD_DEFAULT, "glVertexWeightfEXT");
	glVertexWeightfvEXT = dlsym (RTLD_DEFAULT, "glVertexWeightfvEXT");
	glWeightPointerARB = dlsym (RTLD_DEFAULT, "glWeightPointerARB");
	glWeightbvARB = dlsym (RTLD_DEFAULT, "glWeightbvARB");
	glWeightdvARB = dlsym (RTLD_DEFAULT, "glWeightdvARB");
	glWeightfvARB = dlsym (RTLD_DEFAULT, "glWeightfvARB");
	glWeightivARB = dlsym (RTLD_DEFAULT, "glWeightivARB");
	glWeightsvARB = dlsym (RTLD_DEFAULT, "glWeightsvARB");
	glWeightubvARB = dlsym (RTLD_DEFAULT, "glWeightubvARB");
	glWeightuivARB = dlsym (RTLD_DEFAULT, "glWeightuivARB");
	glWeightusvARB = dlsym (RTLD_DEFAULT, "glWeightusvARB");
	glWindowPos2dARB = dlsym (RTLD_DEFAULT, "glWindowPos2dARB");
	glWindowPos2dvARB = dlsym (RTLD_DEFAULT, "glWindowPos2dvARB");
	glWindowPos2fARB = dlsym (RTLD_DEFAULT, "glWindowPos2fARB");
	glWindowPos2fvARB = dlsym (RTLD_DEFAULT, "glWindowPos2fvARB");
	glWindowPos2iARB = dlsym (RTLD_DEFAULT, "glWindowPos2iARB");
	glWindowPos2ivARB = dlsym (RTLD_DEFAULT, "glWindowPos2ivARB");
	glWindowPos2sARB = dlsym (RTLD_DEFAULT, "glWindowPos2sARB");
	glWindowPos2svARB = dlsym (RTLD_DEFAULT, "glWindowPos2svARB");
	glWindowPos3dARB = dlsym (RTLD_DEFAULT, "glWindowPos3dARB");
	glWindowPos3dvARB = dlsym (RTLD_DEFAULT, "glWindowPos3dvARB");
	glWindowPos3fARB = dlsym (RTLD_DEFAULT, "glWindowPos3fARB");
	glWindowPos3fvARB = dlsym (RTLD_DEFAULT, "glWindowPos3fvARB");
	glWindowPos3iARB = dlsym (RTLD_DEFAULT, "glWindowPos3iARB");
	glWindowPos3ivARB = dlsym (RTLD_DEFAULT, "glWindowPos3ivARB");
	glWindowPos3sARB = dlsym (RTLD_DEFAULT, "glWindowPos3sARB");
	glWindowPos3svARB = dlsym (RTLD_DEFAULT, "glWindowPos3svARB");
	glWriteMaskEXT = dlsym (RTLD_DEFAULT, "glWriteMaskEXT");
	return 1;
}

/**
 * \brief Deinitializes the video subsystem.
 */
void
livid_video_free ()
{
	initialized--;
}

/**
 * \brief Checks if an extension is supported.
 *
 * \param extension Extension string.
 * \return Nonzero if supported.
 */
int
livid_video_check_support (const char* extension)
{
	const GLubyte* extensions = NULL;
	const GLubyte* start;
	GLubyte* where;
	GLubyte* terminator;

	where = (GLubyte*) strchr (extension, ' ');
	if (where || *extension == '\0')
		return 0;
	extensions = glGetString (GL_EXTENSIONS);
	start = extensions;
	while (1)
	{
		where = (GLubyte*) strstr ((const char*) start, extension);
		if (!where)
			break;
		terminator = where + strlen (extension);
		if (where == start || *(where - 1) == ' ')
		{
			if (*terminator == ' ' || *terminator == '\0')
				return 1;
		}
		start = terminator;
	}
	return 0;
}

